'use strict';

exports.__esModule = true;
exports.ESBackend = undefined;

var _ESBackend = require('./ESBackend');

var _ESBackend2 = _interopRequireDefault(_ESBackend);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.ESBackend = _ESBackend2.default; // Generated by CoffeeScript 1.11.1