// Generated by CoffeeScript 1.11.1
var ESBackend,
    extend = function (child, parent) {
  for (var key in parent) {
    if (hasProp.call(parent, key)) child[key] = parent[key];
  }function ctor() {
    this.constructor = child;
  }ctor.prototype = parent.prototype;child.prototype = new ctor();child.__super__ = parent.prototype;return child;
},
    hasProp = {}.hasOwnProperty;

import { Backend, BoundModel, Util, createStandardInstanceClassForBoundModel } from 'ormojo';

import ESBoundModel from './ESBoundModel';

import ESChildModel from './ESChildModel';

import { ESIndex, ESIndices } from './ESIndex';

import ESMigration from './ESMigration';

import ESResultSet from './ESResultSet';

import { makeESAPI } from './ESAPI';

export default ESBackend = function (superClass) {
  extend(ESBackend, superClass);

  function ESBackend(es) {
    this.es = es;
    this.indices = new ESIndices(this);
  }

  ESBackend.prototype.initialize = function () {
    return this.api = makeESAPI(this.es, this.corpus.log, this.corpus.Promise);
  };

  ESBackend.prototype._bindModel = function (clazz, model, bindingOptions) {
    var bm;
    bm = new clazz(model, this, bindingOptions);
    this.indices.addBoundModel(bm);
    return bm;
  };

  ESBackend.prototype.bindModel = function (model, bindingOptions) {
    return this._bindModel(ESBoundModel, model, bindingOptions);
  };

  ESBackend.prototype.bindChildModel = function (childModel, bindingOptions) {
    return this._bindModel(ESChildModel, childModel, bindingOptions);
  };

  ESBackend.prototype.getMigration = function () {
    return new ESMigration(this.corpus, this);
  };

  ESBackend.prototype._deserialize = function (boundModel, esData, instance) {
    if (instance) {
      Object.assign(instance.dataValues, esData._source);
    } else {
      instance = boundModel._createInstance(esData._source);
    }
    if (esData._id) {
      instance._id = esData._id;
    }
    if (esData._index) {
      instance._index = esData._index;
    }
    if (esData._version) {
      instance._version = esData._version;
    }
    if (esData._type) {
      instance._type = esData._type;
    }
    if (esData._score) {
      instance._score = esData._score;
    }
    if (esData._routing) {
      instance._routing = esData._routing;
    }
    if (esData._parent) {
      instance._parent = esData._parent;
    }
    instance._clearChanges();
    return instance;
  };

  ESBackend.prototype.find = function (boundModel, options) {
    return this.api.findRaw(boundModel.getIndex(), boundModel.getDefaultType(), {
      size: 1,
      body: options.elasticsearch_query
    }).then(function (_this) {
      return function (rst) {
        if (!rst || !rst.hits || rst.hits.total === 0) {
          return void 0;
        } else {
          return _this._deserialize(boundModel, rst.hits.hits[0]);
        }
      };
    }(this));
  };

  ESBackend.prototype.findAll = function (boundModel, options) {
    var ref, searchParams;
    searchParams = {};
    searchParams.body = options.elasticsearch_query ? options.elasticsearch_query : (ref = options.cursor) != null ? ref.query : void 0;
    if (options.cursor) {
      searchParams.from = options.cursor.offset;
      searchParams.size = options.cursor.limit;
    } else {
      if (options.offset) {
        searchParams.from = options.offset;
      }
      if (options.limit) {
        searchParams.size = options.limit;
      }
    }
    return this.api.findRaw(boundModel.getIndex(), boundModel.getDefaultType(), searchParams).then(function (_this) {
      return function (rst) {
        var data, x;
        if (!rst || !rst.hits) {
          return new ESResultSet([], 0, 0, null, 0);
        } else {
          data = function () {
            var i, len, ref1, results;
            ref1 = rst.hits.hits;
            results = [];
            for (i = 0, len = ref1.length; i < len; i++) {
              x = ref1[i];
              results.push(this._deserialize(boundModel, x));
            }
            return results;
          }.call(_this);
          return new ESResultSet(data, rst.hits.total, searchParams.from, searchParams.body, rst.hits.max_score);
        }
      };
    }(this));
  };

  ESBackend.prototype._saveNewInstance = function (instance, boundModel) {
    return this.api.createFromInstance(instance, this._deserialize, this);
  };

  ESBackend.prototype._saveOldInstance = function (instance, boundModel) {
    return this.api.updateInstance(instance, this._deserialize, this);
  };

  ESBackend.prototype.save = function (instance, boundModel) {
    if (instance.isNewRecord) {
      return this._saveNewInstance(instance, boundModel);
    } else {
      return this._saveOldInstance(instance, boundModel);
    }
  };

  ESBackend.prototype.destroy = function (instance, boundModel) {
    return this.api.destroyInstance(instance);
  };

  return ESBackend;
}(Backend);