// Generated by CoffeeScript 1.11.1
var ESResultSet,
    extend = function (child, parent) {
  for (var key in parent) {
    if (hasProp.call(parent, key)) child[key] = parent[key];
  }function ctor() {
    this.constructor = child;
  }ctor.prototype = parent.prototype;child.prototype = new ctor();child.__super__ = parent.prototype;return child;
},
    hasProp = {}.hasOwnProperty;

import { ResultSet } from 'ormojo';

import Cursor from './ESCursor';

export default ESResultSet = function (superClass) {
  extend(ESResultSet, superClass);

  function ESResultSet(data, total, offset, searchBody, maxScore) {
    var nextOffset;
    this.total = total;
    this.maxScore = maxScore != null ? maxScore : 0;
    ESResultSet.__super__.constructor.call(this);
    this.results = data || [];
    nextOffset = (offset || 0) + this.results.length;
    if (nextOffset < this.total) {
      this.cursor = new Cursor(searchBody).setFromOffset(nextOffset, this.results.length, this.total);
    }
  }

  ESResultSet.prototype.getTotalResultCount = function () {
    return this.total;
  };

  ESResultSet.prototype.getCursor = function () {
    return this.cursor;
  };

  ESResultSet.prototype.getMaxScore = function () {
    return this.maxScore;
  };

  return ESResultSet;
}(ResultSet);