// Generated by CoffeeScript 1.11.1
var esTypeMap;

import * as ormojo from 'ormojo';

export default esTypeMap = function (orType) {
  var match;
  if (orType === ormojo.STRING) {
    return {
      type: 'string'
    };
  } else if (orType === ormojo.TEXT) {
    return {
      type: 'string'
    };
  } else if (orType === ormojo.INTEGER) {
    return {
      type: 'long'
    };
  } else if (orType === ormojo.BOOLEAN) {
    return {
      type: 'boolean'
    };
  } else if (orType === ormojo.FLOAT) {
    return {
      type: 'double'
    };
  } else if (orType === ormojo.OBJECT) {
    return {
      type: 'object'
    };
  } else if (orType === ormojo.DATE) {
    return {
      type: 'date',
      format: 'strict_date_optional_time||epoch_millis'
    };
  } else if (match = /^ARRAY\((.*)\)$/.exec(orType)) {
    return esTypeMap(match[1]);
  } else {
    return void 0;
  }
};